# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   labels:
#     app: filebeat
#   name: filebeat
#   namespace: kube-system
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   labels:
#     app: filebeat
#   name: filebeat
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - namespaces
#   - pods
#   verbs:
#   - get
#   - watch
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: filebeat
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: filebeat
# subjects:
# - kind: ServiceAccount
#   name: filebeat
#   namespace: kube-system
# ---
--- 
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  labels: 
    k8s-app: filebeat
  name: filebeat
  namespace: kube-system 
 
--- 
kind: ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: filbeat
rules: 
  - apiGroups: 
      - "" 
    resources: 
      - "namespaces" 
      - "pods" 
    verbs: 
      - "list"
      - "get" 
      - "watch" 
 
--- 
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: filbeat 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: filbeat 
subjects: 
- kind: ServiceAccount 
  name: fluentd
  namespace: kube-system