kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch-logging
spec:
  selector:
    app: elasticsearch-logging
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node